name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - backend/**

jobs:
  deploy:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:

      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Build
        run: mvn clean package -DskipTests

      - name: Copy JAR
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ubuntu
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "backend/target/*.jar"
          target: "/root"

      - name: Restart Backend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ubuntu
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo systemctl restart springbootapp.service