name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - frontend/**

jobs:

  deploy:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

      run: echo "${{ secrets.VPS_KEY }}" | wc -c

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 26

      - run: npm ci

      - run: npm run build

      - name: Upload Dist
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ubuntu
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "frontend/dist/*"
          target: "/root/payroll-frontend"

      - name: Reload Frontend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ubuntu
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            pm2 restart payroll-system2